This is just a test to see if i can import the png as a mesh somehow in blender.
I should not assume that those are my values in any dataset. Just for the toy.

In [9]:
import numpy as np
from PIL import Image

In [10]:
stack = np.load('sliced_heat_flux_array_as_toy.npy')

im = stack[0]

In [11]:
np.unique(im)

array([-9.99999900e+06, -1.11634590e+02, -1.07136383e+02, ...,
        1.14487427e+02,  1.14667374e+02,  1.19272026e+02], dtype=float32)

In [12]:
im = np.where(im!=np.min(im), im+113, 0)

np.unique(im)

array([  0.       ,   1.3654099,   5.863617 , ..., 227.48743  ,
       227.66737  , 232.27203  ], dtype=float32)

In [13]:
im = im.astype(np.uint8)

np.unique(im)

array([  0,   1,   5,  13,  14,  16,  17,  19,  20,  21,  22,  23,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 19

In [42]:
im_as_rgba = np.stack((im,im,im, np.where(im==0,0,255).astype(np.uint8)), axis=2)

In [43]:
im_pil = Image.fromarray(im_as_rgba)

In [44]:
im_pil.save('test.png')